# fly.toml app configuration file generated for pokedex-yasen-fso on 2023-08-14T09:13:15+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pokedex-yasen-fso"
primary_region = "ams"


[deploy]
release_command = "npm run build"

[processes]
app = "node app.js"

[build]
[build.args]
NODE_VERSION = "16.20.2"

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]
