# fly.toml app configuration file generated for pokedex-yasen-fso on 2023-08-14T09:13:15+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pokedex-yasen-fso"
primary_region = "ams"


[deploy]
release_command = "npm run build"

[processes]
app = "node app.js"

[build]
[build.args]
NODE_VERSION = "16.20.2"

# [http_service]
# internal_port = 3000
# force_https = true
# auto_stop_machines = true
# auto_start_machines = true
# min_machines_running = 0
# processes = ["app"]

# [tcp_checks]
# grace_period = "1s"
# interval = "15s"
# restart_limit = 0
# timeout = "2s"
# processes = ["app"]


# [http_checks]
# interval = 10000
# grace_period = "5s"
# method = "get"
# path = "/health"
# protocol = "http"
# timeout = 2000
# tls_skip_verify = false
# processes = ["app"]


[service]
internal_port = 3000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0

[service.processes]
app = "node app.js"

[[service.tcp_checks]]
grace_period = "1s"
interval = "15s"
restart_limit = 0
timeout = "2s"

[[service.http_checks]]
interval = 10000
grace_period = "5s"
method = "get"
path = "/health"
protocol = "http"
timeout = 2000
tls_skip_verify = false
