name: Hello World!

on:
  schedule:
    - cron: '30 5,17 * * *'

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
      - name: Today is
        run: |
          date
      - name: Directory content
        run: |
          ls -l
