name: Testing stuff

on:
  push:
    branches:
      - master

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Only runs if message doesn't contain "#skip"
        if: ${{ !contains(toJson(github.event.commits.*.message), '#skip') }}
        run: echo I am running......
